apiVersion: v1
kind: ServiceAccount
metadata:
  name: gh-runner
  namespace: mlops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gh-runner-deployer
  namespace: mlops
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gh-runner-deployer-binding
  namespace: mlops
subjects:
- kind: ServiceAccount
  name: gh-runner
  namespace: mlops
roleRef:
  kind: Role
  name: gh-runner-deployer
  apiGroup: rbac.authorization.k8s.io
